-- ============================================================================
-- DEPRECATED / NOT CANONICAL.
-- The authoritative, up-to-date schema is assembled from the ordered files in
--   docker/init/  (01-schema.sql, 02-seed.sql, 03/04/05 migrations).
-- Those include the supervisor role, users.scope, women.sms_consent, and the
-- reminders table. Do NOT import this file for a real install — import the
-- docker/init/ files in filename order instead (see deploy/RUNBOOK.md).
-- This stub remains only so historical references resolve.
-- ============================================================================
